Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
repo = Repo(CORPUS_PATH)
print_heading("Data and software versions")
print(f"Data repo '{get_repo_name(repo)}' @ {repo.commit().hexsha[:7]}")
print(f"dimcat version {dc.__version__}")
print(f"ms3 version {ms3.__version__}")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNoSuchPathError[0m                           Traceback (most recent call last)
Cell [0;32mIn[3], line 1[0m
[0;32m----> 1[0m repo [38;5;241m=[39m [43mRepo[49m[43m([49m[43mCORPUS_PATH[49m[43m)[49m
[1;32m      2[0m print_heading([38;5;124m"[39m[38;5;124mData and software versions[39m[38;5;124m"[39m)
[1;32m      3[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mData repo [39m[38;5;124m'[39m[38;5;132;01m{[39;00mget_repo_name(repo)[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m @ [39m[38;5;132;01m{[39;00mrepo[38;5;241m.[39mcommit()[38;5;241m.[39mhexsha[:[38;5;241m7[39m][38;5;132;01m}[39;00m[38;5;124m"[39m)

File [0;32m~/.local/lib/python3.10/site-packages/git/repo/base.py:236[0m, in [0;36mRepo.__init__[0;34m(self, path, odbt, search_parent_directories, expand_vars)[0m
[1;32m    234[0m [38;5;28;01mif[39;00m epath [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    235[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m os[38;5;241m.[39mpath[38;5;241m.[39mexists(epath):
[0;32m--> 236[0m         [38;5;28;01mraise[39;00m NoSuchPathError(epath)
[1;32m    238[0m [38;5;66;03m# Walk up the path to find the `.git` dir.[39;00m
[1;32m    239[0m curpath [38;5;241m=[39m epath

[0;31mNoSuchPathError[0m: /home/hentsche/tmp/all_subcorpora

